"""optimize_indexes

Revision ID: 9b6e0da11999
Revises: aee45952fe40
Create Date: 2026-07-17 18:52:44.793346

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b6e0da11999'
down_revision: Union[str, None] = 'aee45952fe40'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_diagnoses_triggered_by_id'), 'diagnoses', ['triggered_by_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_diagnoses_triggered_by_id'), table_name='diagnoses')
    # ### end Alembic commands ###
