"""add_config_to_integrations

Revision ID: f6aa0acfa6b5
Revises: 9b6e0da11999
Create Date: 2026-07-21 19:36:37.010169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f6aa0acfa6b5'
down_revision: Union[str, None] = '9b6e0da11999'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('integrations', sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('integrations', 'config')
    # ### end Alembic commands ###
